all: p1 p3 p6 p9 p12 scheduler

p1: p.c
	gcc p.c -o p1

p3: p.c
	gcc p.c -o p3

p6: p.c
	gcc p.c -o p6

p9: p.c
	gcc p.c -o p9

p12: p.c
	gcc p.c -o p12

scheduler: scheduler.c
	gcc -Wall scheduler.c -o scheduler